workspace:
  base: /home
  path: app

pipeline:
slack:
    image: plugins/slack
    channel: docker_build
    when:
      branch: develop
  docker_build :
    image: plugins/docker
    dockerfile: pipeline/Dockerfile
    registry: registry.cn-shenzhen.aliyuncs.com 
    repo: registry.cn-shenzhen.aliyuncs.com/qtc_test/reaction-admin 
    secrets: [ docker_username, docker_password ]
    tags:
      - latest
 
