workspace:
  base: /home
  path: app

pipeline:
  #docker_build_and_push :
    #image: plugins/docker
    #dockerfile: pipeline/Dockerfile
    #registry: registry.cn-shenzhen.aliyuncs.com 
    #repo: registry.cn-shenzhen.aliyuncs.com/qtc_test/reaction-admin 
    #secrets: [ docker_username, docker_password ]
    #tags:
      #- latest
  deploy:
    image: appleboy/drone-ssh # 用于连接服务器
    host:
      - 192.168.200.32
    port: 22
    secrets: [ ssh_username, ssh_password ]
    command_timeout: 300 # ssh命令行执行超时时间，300秒
    script:
      - docker  pull registry.cn-shenzhen.aliyuncs.com/qtc_test/reaction-admin:latest
      - docker  rm -f reaction-admin || true # 因如果不存在，rm会报错
      - docker run -d -p 8065:8065 --name reaction-admin registry.cn-shenzhen.aliyuncs.com/qtc_test/reaction-admin
      - docker ps 
    when:
      branch: [master]
      event: [push]
   
