workspace:
  base: /home
  path: app

pipeline:
  deploy:
    image: appleboy/drone-ssh # 用于连接服务器
    host:
      - 192.168.200.32
    username: root
    password: Quantum2018!
    port: 22
    command_timeout: 300 # ssh命令行执行超时时间，300秒
    script:
      - service docker start
      - docker  pull registry.cn-shenzhen.aliyuncs.com/qtc_test/reaction-admin:latest
      - docker  rm -f reaction-admin || true # 因如果不存在，rm会报错
      - docker images #
      - docker run -d -p 8065:8065 --name reaction-admin registry.cn-shenzhen.aliyuncs.com/qtc_test/reaction-admin
 
