workspace:
  base: /home
  path: app

pipeline:
  docker_build:
    image: plugins/docker
    dockerfile: pipeline/Dockerfile
    repo: reaction-admin
    tags: true
  
  deploy:
      image: reaction-admin
      commands:
      script:
        - cd /home/app
        - pwd
        - echo "hello world"
