workspace:
  base: /home
  path: app

pipeline:
    docker_build:
    image: plugins/docker
    dockerfile: pipeline/Dockerfile
    repo: registry.cn-shenzhen.aliyuncs.com/qtc_test/reaction-admin
    registry: reaction-admin
    secrets: [ docker_username, docker_password ]
  
  deploy:
      image: reaction-admin
      commands:
      script:
        - cd /home/app
        - pwd
        - echo "hello world"
