workspace:
  base: /home
  path: app

pipeline:
- build:
    image: golang
    commands:
    - go build
    - go test

trigger:
  branch:
  - master
  event:
  - push
- docker_build :
    image: plugins/docker
    dockerfile: pipeline/Dockerfile
    registry: registry.cn-shenzhen.aliyuncs.com 
    repo: registry.cn-shenzhen.aliyuncs.com/qtc_test/reaction-admin 
    secrets: [ docker_username, docker_password ]
    tags:
      - latest
