workspace:
  base: /home
  path: app

pipeline:
  build:
    image: plugins/docker
    commands:
      - cd /home/app
      - pwd
 branches: master
  publish:
      image: plugins/docker
      registry: registry.cn-shenzhen.aliyuncs.com/qtc_test/# 仓库
      repo: reaction-admin # docker仓库地址
      # mirror: https://docker.mirrors.ustc.edu.cn
      # 需要使用drone cli添加secrets: http://docs.drone.io/manage-secrets/
      secrets: [ docker_username, docker_password ]
      tags:
        - 0.0.1

  deploy:
      image: reaction-admin
      commands:
      script:
        - cd /home/app
        - pwd
        - echo "hello world"
