# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: "TODO: set repository"
  tag: "TODO: set tag"
  pullPolicy: IfNotPresent
  pullSecrets: alicloud-registry-key
service:
  type: LoadBalancer
  externalPort: 443
  internalPort: 80
  annotations:
    service.beta.kubernetes.io/alicloud-loadbalancer-ProtocolPort: 'https:443'
    service.beta.kubernetes.io/alicloud-loadbalancer-CertID: 1811066757327101_161e4ddaf08_-543902569_14586787
    service.beta.kubernetes.io/alicloud-loadbalancer-ChargeType: paybytraffic
    service.beta.kubernetes.io/alicloud-loadbalancer-HealthCheckFlag: 'off'
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
