apiVersion: v1
kind: Service
metadata:
  name: {{ template "sanbao-admin.name" . }}
  labels:
    app: {{ template "sanbao-admin.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
# {{- if eq .Release.Namespace "production" -}}
    # service.beta.kubernetes.io/alicloud-loadbalancer-id: lb-wz9f1h7l4z5fh1ts7bhyc
# {{- else if eq .Release.Namespace "staging" -}}
#     service.beta.kubernetes.io/alicloud-loadbalancer-id: lb-wz9hldlurot1xct8r3cko
# {{- end -}}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app: {{ template "sanbao-admin.name" . }}
    release: {{ .Release.Name }}
